import React, { useState, useEffect } from 'react';
import { employeeAPI, departmentAPI, teamAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import BackButton from '../components/BackButton';
import './Employees.css';

const Employees = () => {
    const { user } = useAuth();
    const toast = useToast();
    const [employees, setEmployees] = useState([]);
    const [departments, setDepartments] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showModal, setShowModal] = useState(false);
    const [showViewModal, setShowViewModal] = useState(false);
    const [showAssignModal, setShowAssignModal] = useState(false);
    const [selectedEmployee, setSelectedEmployee] = useState(null);
    const [selectedManager, setSelectedManager] = useState('');
    const [searchQuery, setSearchQuery] = useState('');
    const [formData, setFormData] = useState({
        employeeId: '',
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        designation: '',
        departmentId: ''
    });

    const isManager = user?.role === 'MANAGER';
    const canManageEmployees = user?.role === 'ADMIN' || user?.role === 'HR';

    useEffect(() => {
        fetchEmployees();
        fetchDepartments();
    }, []);

    const fetchEmployees = async () => {
        try {
            setLoading(true);
            let response;
            if (isManager) {
                response = await employeeAPI.getMyTeam();
            } else {
                response = await employeeAPI.getAll();
            }
            setEmployees(response.data);
        } catch (error) {
            console.error('Error fetching employees:', error);
            if (isManager) {
                setEmployees([]);
            }
        } finally {
            setLoading(false);
        }
    };

    const fetchDepartments = async () => {
        try {
            const response = await departmentAPI.getAll(true);
            setDepartments(response.data);
        } catch (error) {
            console.error('Error fetching departments:', error);
        }
    };

    const handleSearch = async (e) => {
        const query = e.target.value;
        setSearchQuery(query);
    };

    // Filter employees locally for table search
    const filteredEmployees = employees.filter(emp => {
        const query = searchQuery.toLowerCase();
        return (
            emp.firstName?.toLowerCase().includes(query) ||
            emp.lastName?.toLowerCase().includes(query) ||
            emp.email?.toLowerCase().includes(query) ||
            emp.employeeId?.toLowerCase().includes(query)
        );
    });

    const [createdEmployeeCredentials, setCreatedEmployeeCredentials] = useState(null);

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            if (selectedEmployee) {
                await employeeAPI.update(selectedEmployee.id, formData);
                toast.success('Employee updated successfully!');
                setShowModal(false);
                resetForm();
            } else {
                const response = await employeeAPI.create(formData);
                const data = response.data;

                if (data.autoGeneratedPassword) {
                    setCreatedEmployeeCredentials({
                        username: data.generatedUsername,
                        password: data.autoGeneratedPassword,
                        name: `${formData.firstName} ${formData.lastName}`
                    });
                    setShowModal(false);
                    // Don't reset form yet or close modal completely until user acknowledges credentials? 
                    // Actually, we close the form modal and open credentials modal.
                    resetForm();
                } else {
                    toast.success('Employee created successfully!');
                    setShowModal(false);
                    resetForm();
                }
            }
            fetchEmployees();
        } catch (error) {
            toast.error(error.response?.data?.error || error.message || 'An error occurred');
        }
    };

    const handleEdit = (employee) => {
        setSelectedEmployee(employee);
        setFormData({
            employeeId: employee.employeeId || '',
            firstName: employee.firstName || '',
            lastName: employee.lastName || '',
            email: employee.email || '',
            phone: employee.phone || '',
            designation: employee.designation || '',
            departmentId: employee.department?.id || ''
        });
        setShowModal(true);
    };

    const handleView = (employee) => {
        setSelectedEmployee(employee);
        setShowViewModal(true);
    };

    const resetForm = () => {
        setFormData({
            employeeId: '',
            firstName: '',
            lastName: '',
            email: '',
            phone: '',
            designation: '',
            departmentId: ''
        });
        setSelectedEmployee(null);
    };

    const handleDeactivate = async (id) => {
        if (window.confirm('Are you sure you want to deactivate this employee?')) {
            try {
                await employeeAPI.deactivate(id);
                toast.success('Employee deactivated successfully!');
                fetchEmployees();
            } catch (error) {
                toast.error('Error deactivating employee');
            }
        }
    };

    const handleActivate = async (id) => {
        if (window.confirm('Are you sure you want to activate this employee?')) {
            try {
                await employeeAPI.activate(id);
                toast.success('Employee activated successfully!');
                fetchEmployees();
            } catch (error) {
                toast.error('Error activating employee');
            }
        }
    };

    const handleAssignManager = (employee) => {
        setSelectedEmployee(employee);
        setSelectedManager(employee.reportingManager?.id || '');
        setShowAssignModal(true);
    };

    const handleSaveManagerAssignment = async () => {
        try {
            await teamAPI.assignToManager(selectedEmployee.id, selectedManager || null);
            toast.success(selectedManager ? 'Employee assigned to manager successfully!' : 'Manager assignment removed!');
            setShowAssignModal(false);
            fetchEmployees();
        } catch (error) {
            toast.error(error.response?.data?.error || 'Failed to assign manager');
        }
    };

    return (
        <div className="employees-page">
            <BackButton to="/dashboard" label="Back to Dashboard" />
            <div className="employees-header">
                <h1>{isManager ? 'My Team' : '👥 Employees Directory'}</h1>
                {canManageEmployees && (
                    <button
                        className="btn btn-primary"
                        onClick={() => {
                            resetForm();
                            setShowModal(true);
                        }}
                    >
                        + Add Employee
                    </button>
                )}
            </div>

            <div className="search-bar">
                <input
                    type="text"
                    placeholder="🔍 Search by name, ID or email..."
                    value={searchQuery}
                    onChange={handleSearch}
                />
            </div>

            {loading ? (
                <div className="loading">Loading...</div>
            ) : (
                <div className="table-container glass-card">
                    <table className="employees-table">
                        <thead>
                            <tr>
                                <th>Agent</th>
                                <th>Details</th>
                                <th>Role/Designation</th>
                                <th>Status</th>
                                {(canManageEmployees || isManager) && <th>Actions</th>}
                            </tr>
                        </thead>
                        <tbody>
                            {filteredEmployees.length > 0 ? (
                                filteredEmployees.map((employee) => (
                                    <tr key={employee.id}>
                                        <td>
                                            <div className="employee-cell">
                                                <div className="employee-avatar-small">
                                                    {employee.photoUrl ? (
                                                        <img src={employee.photoUrl} alt="Avatar" />
                                                    ) : (
                                                        `${employee.firstName?.[0]}${employee.lastName?.[0]}`
                                                    )}
                                                </div>
                                                <div className="employee-name-id">
                                                    <span className="name">{employee.firstName} {employee.lastName}</span>
                                                    <span className="id">{employee.employeeId}</span>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div className="contact-info">
                                                <div className="info-row">📧 {employee.email}</div>
                                                <div className="info-row">📞 {employee.phone}</div>
                                                <div className="info-row">🏢 {employee.department?.name || 'N/A'}</div>
                                            </div>
                                        </td>
                                        <td>
                                            <div className="role-info">
                                                <span className="designation">{employee.designation || 'N/A'}</span>
                                                {employee.reportingManager && (
                                                    <span className="manager-tag">
                                                        Mgr: {employee.reportingManager.firstName}
                                                    </span>
                                                )}
                                            </div>
                                        </td>
                                        <td>
                                            <span className={`status-badge ${employee.status?.toLowerCase()}`}>
                                                {employee.status}
                                            </span>
                                        </td>
                                        {(canManageEmployees || isManager) && (
                                            <td>
                                                <div className="action-buttons">
                                                    <button onClick={() => handleView(employee)} className="btn-icon" title="View Details">👁️</button>
                                                    {canManageEmployees && (
                                                        <>
                                                            <button onClick={() => handleEdit(employee)} className="btn-icon" title="Edit">✏️</button>
                                                            <button onClick={() => handleAssignManager(employee)} className="btn-icon" title="Assign Manager">👔</button>
                                                            {employee.status === 'ACTIVE' ? (
                                                                <button onClick={() => handleDeactivate(employee.id)} className="btn-icon danger" title="Deactivate">🗑️</button>
                                                            ) : (
                                                                <button onClick={() => handleActivate(employee.id)} className="btn-icon success" title="Activate">✅</button>
                                                            )}
                                                        </>
                                                    )}
                                                </div>
                                            </td>
                                        )}
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan={(canManageEmployees || isManager) ? 5 : 4} className="no-data">
                                        No employees found.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            )}

            {/* View Modal */}
            {showViewModal && selectedEmployee && (
                <div className="modal-overlay" onClick={() => setShowViewModal(false)}>
                    <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                        <h2>Employee Details</h2>
                        <div className="view-profile-header">
                            <div className="profile-avatar-large">
                                {selectedEmployee.photoUrl ? (
                                    <img src={selectedEmployee.photoUrl} alt="Avatar" />
                                ) : (
                                    `${selectedEmployee.firstName?.[0]}${selectedEmployee.lastName?.[0]}`
                                )}
                            </div>
                            <div className="profile-title">
                                <h3>{selectedEmployee.firstName} {selectedEmployee.lastName}</h3>
                                <span className={`status-badge ${selectedEmployee.status?.toLowerCase()}`}>
                                    {selectedEmployee.status}
                                </span>
                            </div>
                        </div>

                        <div className="view-grid">
                            <div className="view-section">
                                <h4>Professional Info</h4>
                                <div className="info-item"><label>ID:</label> <span>{selectedEmployee.employeeId}</span></div>
                                <div className="info-item"><label>Designation:</label> <span>{selectedEmployee.designation || '-'}</span></div>
                                <div className="info-item"><label>Department:</label> <span>{selectedEmployee.department?.name || '-'}</span></div>
                                <div className="info-item"><label>Role:</label> <span>{selectedEmployee.user?.role || '-'}</span></div>
                                <div className="info-item"><label>Manager:</label> <span>{selectedEmployee.reportingManager ? `${selectedEmployee.reportingManager.firstName} ${selectedEmployee.reportingManager.lastName}` : 'None'}</span></div>
                            </div>

                            <div className="view-section">
                                <h4>Contact Info</h4>
                                <div className="info-item"><label>Email:</label> <span>{selectedEmployee.email}</span></div>
                                <div className="info-item"><label>Phone:</label> <span>{selectedEmployee.phone}</span></div>
                                <div className="info-item"><label>City/State:</label> <span>{selectedEmployee.city ? `${selectedEmployee.city}, ${selectedEmployee.state}` : '-'}</span></div>
                            </div>

                            <div className="view-section">
                                <h4>Personal Info</h4>
                                <div className="info-item"><label>DOB:</label> <span>{selectedEmployee.dateOfBirth || '-'}</span></div>
                                <div className="info-item"><label>Blood Group:</label> <span>{selectedEmployee.bloodGroup || '-'}</span></div>
                                <div className="info-item"><label>Emergency Contact:</label> <span>{selectedEmployee.emergencyContactName || '-'} ({selectedEmployee.emergencyContactPhone || '-'})</span></div>
                            </div>
                        </div>

                        <div className="modal-actions">
                            <button type="button" onClick={() => setShowViewModal(false)}>Close</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Create/Edit Modal */}
            {showModal && (
                <div className="modal-overlay" onClick={() => setShowModal(false)}>
                    <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                        <h2>{selectedEmployee ? 'Edit Employee' : 'Add New Employee'}</h2>
                        <form onSubmit={handleSubmit}>
                            <div className="form-grid">
                                <input
                                    type="text"
                                    placeholder="Employee ID *"
                                    value={formData.employeeId}
                                    onChange={(e) => setFormData({ ...formData, employeeId: e.target.value })}
                                    required
                                />
                                <input
                                    type="text"
                                    placeholder="First Name *"
                                    value={formData.firstName}
                                    onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                                    required
                                />
                                <input
                                    type="text"
                                    placeholder="Last Name *"
                                    value={formData.lastName}
                                    onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                                    required
                                />
                                <input
                                    type="email"
                                    placeholder="Email *"
                                    value={formData.email}
                                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                    required
                                />
                                <input
                                    type="tel"
                                    placeholder="Phone *"
                                    value={formData.phone}
                                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                                    required
                                />
                                <input
                                    type="text"
                                    placeholder="Designation"
                                    value={formData.designation}
                                    onChange={(e) => setFormData({ ...formData, designation: e.target.value })}
                                />
                                <select
                                    value={formData.departmentId}
                                    onChange={(e) => setFormData({ ...formData, departmentId: e.target.value })}
                                >
                                    <option value="">Select Department</option>
                                    {departments.map(dept => (
                                        <option key={dept.id} value={dept.id}>{dept.name}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="modal-actions">
                                <button type="button" onClick={() => setShowModal(false)}>Cancel</button>
                                <button type="submit" className="btn-primary">
                                    {selectedEmployee ? 'Update' : 'Create'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Assign Manager Modal */}
            {showAssignModal && (
                <div className="modal-overlay" onClick={() => setShowAssignModal(false)}>
                    <div className="modal-content small-modal" onClick={(e) => e.stopPropagation()}>
                        <h2>Assign to Manager</h2>
                        <p className="modal-employee-name">
                            {selectedEmployee?.firstName} {selectedEmployee?.lastName}
                        </p>
                        <select
                            value={selectedManager}
                            onChange={(e) => setSelectedManager(e.target.value)}
                            style={{ width: '100%', padding: '12px', marginBottom: '20px' }}
                        >
                            <option value="">No Manager (Remove Assignment)</option>
                            {employees
                                .filter(emp =>
                                    emp.id !== selectedEmployee?.id &&
                                    emp.user &&
                                    ['MANAGER', 'ADMIN', 'HR'].includes(emp.user.role)
                                )
                                .map(manager => (
                                    <option key={manager.id} value={manager.id}>
                                        {manager.firstName} {manager.lastName} - {manager.designation}
                                    </option>
                                ))
                            }
                        </select>
                        <div className="modal-actions">
                            <button type="button" onClick={() => setShowAssignModal(false)}>Cancel</button>
                            <button className="btn-primary" onClick={handleSaveManagerAssignment}>
                                Save
                            </button>
                        </div>
                    </div>
                </div>
            )}
            {/* Credentials Modal */}
            {createdEmployeeCredentials && (
                <div className="modal-overlay">
                    <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                        <h2>🎉 Employee Created!</h2>
                        <div className="credentials-box" style={{
                            background: 'rgba(var(--primary-rgb), 0.1)',
                            padding: '20px',
                            borderRadius: '12px',
                            margin: '20px 0',
                            border: '1px solid rgba(var(--primary-rgb), 0.3)'
                        }}>
                            <p style={{ marginBottom: '15px' }}>
                                A user account has been auto-created for <strong>{createdEmployeeCredentials.name}</strong>.
                                Please share these temporary credentials with them.
                            </p>
                            <div className="credential-row" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                                <strong>Username:</strong>
                                <span style={{ fontFamily: 'monospace', fontSize: '1.1em' }}>{createdEmployeeCredentials.username}</span>
                            </div>
                            <div className="credential-row" style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <strong>Password:</strong>
                                <span style={{ fontFamily: 'monospace', fontSize: '1.2em', background: '#333', padding: '2px 8px', borderRadius: '4px', color: '#fff' }}>
                                    {createdEmployeeCredentials.password}
                                </span>
                            </div>
                        </div>
                        <p style={{ fontSize: '0.9em', color: '#888', marginBottom: '20px' }}>
                            * The employee will be required to change this password upon first login.
                        </p>
                        <div className="modal-actions">
                            <button className="btn-primary" onClick={() => setCreatedEmployeeCredentials(null)}>
                                Done & Close
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Employees;
